settings.cfg.example
tests/scraper/connections/test_github.py
tests/scraper/test_integration.py
tests/testdata/test.bar.yaml
zubbi/default_settings.py
zubbi/models.py
zubbi/scraper/connections/gerrit.py
zubbi/scraper/connections/github.py
zubbi/scraper/main.py
zubbi/scraper/repos/gerrit.py
zubbi/scraper/repos/github.py
zubbi/scraper/tenant_parser.py
zubbi/views.py

Although the connections were created dynamically, most scraper parts were
relying on a connection named "github" (as this was the only one we had so far).
This change removes this assumption and searches for the right connection and
repository provider based on the tenant sources and the configured connections
in the settings.cfg file.

Make scraper independent of GitHub connection

---

zubbi/scraper/scraper.py

After changing the scraper/repository API, non-directory roles are not excluded any longer, as plain git has no knowledge about directories, but only files. This change restores the old behaviour to ignore those cases.

Fix: Ignore files in roles dir and empty role directories

---

settings.cfg.example
zubbi/default_settings.py
zubbi/scraper/main.py

When using the scraper in periodic mode, we were relying on the ZMQ connection
to be configured. Although, there might be cases, where somebody want to use
Zubbi without webhooks. Therefore, the ZMQ connection is now optional. If not
configured, Zubbi scraper will scrape outdated repositories in the specified
interval and just wait in between (instead of listening to ZMQ messages).

Make ZMQ optional

---

zubbi/scraper/main.py

When the repository could not be scraped because of a config error
(wrong connection name), we don't want to delete the outdated data
as this would delete all data for this repository.

Don't delete repository data in case of a config error

---

zubbi/scraper/main.py

Previously, we only deleted repositores explicitly for a GitHub delete
event (repository, installation). However, if we miss such an event, we
will never delete this repository and always try to scrape it, although
it is not accessible anylonger. Even a fresh scraper run won't help,
because the repository is still in Elasticsearch and, in a normal case,
we won't receive a second deletion event for this repository from GitHub.

Always delete outdated repositories

---

zubbi/doc.py

If a wrong variable type is used within the zuul:rolevar directive,
the ZuulSphinx plugin raises a KeyError rather than a SphinxBuildError.
With this change we also catch those Exceptions to not make Zubbi the
zubbi scraper fail because of an invalid README file.

Catch broader exceptions in Sphinx build

---

.gitignore
docker/Dockerfile
docker/docker-compose.yaml
docker/settings.cfg
docker/tenant-config.yaml

With this change, it's easy to get the whole stack up and running. The
docker-compose file will start all necessary services and scrapes the
openstack-infra/zuul-jobs once to get some initial data:
```
$ cd docker
$ docker-compose build
$ docker-compose up
```

Create Dockerfile for zubbi and start the whole stack with docker-compose

---

zubbi/scraper/repos/github.py

We are assuming that the roles/ directory contains only directories (as
every role must be a directory). When this is not the case and we are
tring to list a file, github3.py throws an UnprocessableResponseBody
error which is catched by this change.

Fix listing of non-directories in GitHub

---

settings.cfg.example
tests/scraper/connections/test_gerrit.py
tests/scraper/connections/test_init.py
zubbi/scraper/connections/gerrit.py
zubbi/scraper/repos/gerrit.py
zubbi/templates/details.html

Unfortunately, the Gerrit web URLs (used for browsing directories and 
showing files) are completely different and depending on the tool that is
used for the Gerrit "web endpoint". This change supports the usage of cgit
and gitweb as Gerrit web endpoint and builds the URLs accordingly.
I've discovered a third tool called "gitiles", which is not covered by this
change.

Build Gerrit web URLs based on the "gitweb type" (cgit/gitweb)

---

CHANGELOG.md
README.md
docker/settings.cfg
settings.cfg.example
zubbi/scraper/connections/gerrit.py

1. So far, the credentials were optional in the underlying GitConnection,
but had to be set in the GerritConnection. This change makes them now
really optional.
2. This makes use of the newest changes (cgit implementation) to enable
the Gerrit links on a block's details page.

Make Gerrit credentials optional and update zubbi-demo config

---

docker/Dockerfile

-  fix the build of pyzmq when installing by pip3

Upgrade docker alpine from 3.7 to 3.9

---

CHANGELOG.md
zubbi/static/style.css
zubbi/templates/details.html
zubbi/templates/includes/block-changelog.html
zubbi/templates/includes/block-description.html

When extending Zubbi, someone can now add new tabs (in addition to the
already existing 'Description' and 'Changelog').

Allow custom tabs/contents on the details page

---

CHANGELOG.md
settings.cfg.example
tests/test_elasticsearch.py
zubbi/models.py
zubbi/scraper/main.py

This is only a hack as the 'official' pattern described in the
elasticsearch-dsl documentation does not work as expected. Once
this is working, we should remove this hack and use the official
pattern instead.
For a  detailed description see https://github.com/bmwcarit/zubbi/issues/37#issuecomment-467775826
I've also added some tests for elasticsearch.
Should fix https://github.com/bmwcarit/zubbi/issues/37

Overwrite ES index names with prefix from config, add tests for elasticsearch

---

tests/scraper/test_repo_parser.py

Due to a change in the zuul-sphinx dependency, the type of role vars
is now included in the rendered RST description. Adapted necessary
test cases to include the new parts in the expected output.

Adapt parse test to upstream change in zuul-sphinx

---

tests/conftest.py
tests/scraper/test_events.py
tests/testdata/payloads/github-webhook-installation-created.json
tests/testdata/payloads/github-webhook-installation-deleted.json
tests/testdata/payloads/github-webhook-push.json
zubbi/scraper/main.py

Changes:
37ee31c (Felix Schmidt, 3 months ago)
Add mocked tests for GitHub webhook handling
4a2c4ce (Felix Schmidt, 3 hours ago)
Improve logging in webhook handle functions
30ee71b (Felix Schmidt, 4 months ago)
Remove unused 'config' parameter from event_* methods
4231e11 (Felix Schmidt, 19 hours ago)
Reinitialize installation map if repo is not found during push event
In this case, we might have missed the appropriate create/add event for
this repository and thus need to re-initialize our installatino map.

Fix push event handling for missing repositories, add tests and improve logging

---

CHANGELOG.md
zubbi/scraper/main.py
zubbi/scraper/repos/github.py

a8312e7 (Felix Schmidt, 17 minutes ago)
Avoid splitting invalid GH repository names
This invalid repo name actually comes from a bug in the tenant config 
parser, which results in a repo 'include' that cannot be split into
(owner, /, repo). Thus, the error should be fixed directly in the tenant 
parser. Still, I find it's a good idea to make this part more robust and
avoid similar errors in the future.
d973b9a (Felix Schmidt, 18 hours ago)
Update repo information in ES directly after scraping
Previously, the repo information for all scraped repositories was updated
after all repos were scraped. If the scraping of a single repository
failed, none of the repos were updated in ES.
As the repo information itself are only used for the `list-repos` command
so far, this is not a blocker, but …

Fix some bugs in the repo parser and update repo information is ES directly after scraping

---

CHANGELOG.md
settings.cfg.example
tests/test_elasticsearch.py
zubbi/models.py

Changes:
84d505b (Felix Schmidt, 26 seconds ago)
Update CHANGELOG and settings.cfg.example
09b8fa6 (Felix Schmidt, 2 hours ago)
Remove es_ prefix from index_prefix param for ES init function
bd93a76 (Felix Schmidt, 2 hours ago)
Simplify notation for Elasticsearch configuration in config file
This simplifies the notation for the Elasticsearch configuration in the
settings.cfg. While the old format 'ES_*' is still compatible, we should
remove that some time.
3309649 (Felix Schmidt, 2 hours ago)
Allow SSL context options for Elasticsearch connection

Allow SSL parameters for ES connection and simplify ES notation in settings file

---

zubbi/scraper/main.py

The handle_event() method was adapted somewhen in the past and it looks
like we didn't check this method in the meantime.

Remove unnecessary config parameter for handle_event() method

---

Pipfile.lock
test-requirements.txt
tests/conftest.py
tests/scraper/test_repo_parser.py
zubbi/scraper/connections/github.py
zubbi/scraper/tenant_parser.py

The currently used endpoint to retrieve the access tokens for an
installation was marked as deprecated a long time ago and will be
removed [1]:
/installations/:installation_id/access_tokens
Thus, we switch to the new one:
/app/installations/:installation_id/access_tokens
[1] https://developer.github.com/changes/2020-04-15-replacing-create-installation-access-token-endpoint

Update the Github installation token url

---

CHANGELOG.md
zubbi/models.py
zubbi/scraper/main.py

So far, the delete outdated query wasn't working for Github repositories at all due the slash that's usually contained in the repository name. This fix adds a Keyword field to the repo_name which will allow matching against whole repo names including the slash.

Fix deletion of outdated repositories

---

CHANGELOG.md
zubbi/scraper/main.py

This was done to not copy the code in two places. However, initializing
the connections in the base command function will also be done if
somebody used the --help option or provided invalid paramaters for the
scrape command. In those cases the connections would be initialized
before the actual command and its options are evaluated.

Don't initialize connections in base command function

---

CHANGELOG.md

As I just noticed that it's not necessary to recreate the index since
we are just adding a new field type to an existing property, but do
not change the property's type itself.

Remove note about index recreation in changelog

---

.pre-commit-config.yaml
Pipfile.lock
zubbi/scraper/connections/github.py

This updates the dependencies to their newest version and adapts the pre-commit config to make the black pre-commit hook work with python version >= 3.6.

Update dependencies to newest version

---

CHANGELOG.md
tests/conftest.py
tests/scraper/test_repo_parser.py
tests/test_doc.py
tests/testdata/readmes/reusable.rst
tests/testdata/repo_files/roles/foo/README.rst
tests/testdata/repo_files/zuul.d/jobs.yaml
zubbi/doc.py
zubbi/models.py
zubbi/scraper/repo_parser.py
zubbi/templates/search.html

Not all roles and jobs in the configured tenants are meant to be reusable by others. In order to improve the search result in Zubbi, we add a new directive "reusable" to job description and roles' readme file to specify those meant to be reusable. And they will be displayed on top of the search result list.

Implement 'reusable' directive for boosting reusable roles/jobs

---

CHANGELOG.md
tests/scraper/test_events.py
tests/scraper/test_repo_parser.py
tests/testdata/repo_files/zuul.d/jobs.yaml
zubbi/models.py
zubbi/scraper/main.py
zubbi/scraper/repo_parser.py

When a repo is configured as reusable, all jobs and roles scraped from this repo are labled as "reusable" in zubbi.

Repos can be configured as reusable

---

Pipfile.lock
test-requirements.txt
tests/scraper/test_repo_parser.py
tests/test_doc.py
zubbi/scraper/repos/github.py

Currently, the master branch is hardcoded in the GraphQL query that is used
to retrieve the blame information for a file in a GitHub repository.
Therefore, this query fails in case the repository doesn't provide a master
branch or uses a different default branch name.
This can be fixed by using the defaultBranchRef object which is provided by
the GitHub GraphQL.
To make the whole constrcut a little less error-prone, wrap the evaluation
of the GraphQL response into a try/catch block, so we don't fail in case
the response is not as expected.

Make GraphQL blame query work without master branch

---

CHANGELOG.md
tests/conftest.py
tests/scraper/connections/test_git.py
tests/scraper/test_integration.py
zubbi/scraper/main.py
zubbi/scraper/repos/__init__.py
zubbi/scraper/repos/git.py
zubbi/scraper/repos/github.py
zubbi/scraper/scraper.py
zubbi/scraper/tenant_parser.py

- Zuul job definition files are now parsed recursively
- Zubbi-scraper does not crash anymore if the TENANT_SOURCES_REPO setting references an unknown connection
See commit messages for further details.

Fix zubbi-scraper startup bugs

---

tests/conftest.py
tests/scraper/connections/test_github.py

This seems to cause an issue with our security guidelines, so let's use
something less token-looking-like for the unittests.

Rename token in fixture for unittests

---

tox.ini

This has changed in the meantime, see https://github.com/pypa/pipenv/pull/5200.

Update pipenv command to generate requirements file

---

zubbi/scraper/main.py
zubbi/scraper/repo_parser.py
zubbi/scraper/scraper.py

**[Filter job files for .yaml extension before parsing](https://github.com/bmwcarit/zubbi/pull/94/commits/6f8c248c13958c33b80fa9bb89032c3bd7f05eb6)**
Zubbi expects the zuul.d directory to only contain valid yaml files.
Having something like a README.md file in between the job files will
make the parser fail as it doesn't contain valid yaml.
However, having such a file is totally fine for Zuul, so we should
adapt.
As a first step, we filter for `.yaml´ files in the scraper, so that the
parser doesn't need to take care of that.
**[Make RepoParser more robust against yaml errors](https://github.com/bmwcarit/zubbi/pull/94/commits/5edff9da78754cb2244eff449e8caeadb839a815)**
Even when filtering only for `.yaml` files in the scraper, we might end
up with a file that contains invalid yaml. Thus, …

Filter job files for .yaml extension and make parser more robust

---

.pre-commit-config.yaml
CHANGELOG.md
Pipfile.lock
test-requirements.txt
tests/scraper/test_integration.py
tox.ini
zubbi/scraper/scraper.py

Currently, zubbi-scraper crashes when a repository is empty as we except
the root directoy to exist [1].
Theoretically, we already have tests for that in place, but the mocked
repository class also ensures that the repository root always exists.
To fix this, we catch the CheckOutError which is returned by our GitHub
connection class and adapt our test classes accordingly to cover the
case of a "missing root directory" in a repository.
[1]:
2022-11-21T15:55:25Z DEBUG [zubbi.scraper.repos.github] Listing contents of '/' directory
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/zubbi/scraper/repos/github.py", line 75, in directory_contents
remote_directory = self._repo.directory_contents(
File "/usr/local/lib/python3.8/dist-packages/github3/repos/repo.py", …

Don't let zubbi-scraper crash on empty repositories

---

CHANGELOG.md
zubbi/scraper/main.py

Using the default python dateformat also provides the milliseconds for
each log message and makes them look similar to other python
applications.
This also prepares the changelog for version 2.4.8.

Switch to the default python dateformat for log messages

---

tests/test_elasticsearch.py
zubbi/models.py

We face quite a lot of connection timeouts to Elasticsearch when writing
larger bunches of data.
As a first step, allow additional connection parameters to be set during
client initialization. This will allow us to configure a connection
timeout and other parameters (like a retry) in our deployment.
Additionally, make the writing step more robust by catching any
ElasticsearchException that might arise.

Allow connection timeout to be set on Elasticsearch connection

---

tests/conftest.py
tests/scraper/test_integration.py
tests/scraper/test_repo_parser.py
tests/testdata/repo_files/zuul-extra.d/extra-jobs.yaml
tests/testdata/test.foo.yaml
zubbi/scraper/main.py
zubbi/scraper/repo_parser.py
zubbi/scraper/scraper.py
zubbi/scraper/tenant_parser.py

When creating/updating repo_map, 'extra-config-paths' list is extracted from tenant configuration and saved in repo's 'tenants' dictionary (next to 'jobs' and 'roles')
Extra-config-paths values are used for Scraper class initialization. The 'scrape_job_files' method extends the whitelist with it
'test_integration' tests were extended to verify this new functionality

tenant_parser.py: add support for extra-config-paths

---

CHANGELOG.md
tests/scraper/test_tenant_parser.py
tests/testdata/tenant_configs/tenant-config.yaml
zubbi/scraper/tenant_parser.py

The latest change introduced a bug that failed to parse the following
configuration snippets [1] in a tenant-config.yaml file.
This kind of configuration wasn't supported by Zubbi before, but also
didn't fail when parsing the tenant configuration file. For now,
explicitly ignore this kind of configuration.
Additionally, we also add an explicit test for the tenant parser with
a variety of project configs to catch those errors more easily.
This change also fixes the exclusion of jobs from a project, which
didn't work properly due to the usage of "jobs" instead of "job".
[1]:
- include: []
projects:
- foo
- bar
- exclude:
- job
- semaphore
projects:
- foo

Fix creation of repo map in TenantParser

---

CHANGELOG.md
zubbi/scraper/main.py

This prevents the `extra-config-paths` feature to work correctly.

Fix typo in extra_config_paths variable

---

tests/conftest.py
tests/scraper/test_integration.py
tests/scraper/test_repo_parser.py
tests/testdata/repo_files/roles/foobar/baz/README.rst
zubbi/scraper/scraper.py

Changing the way how roles are scraped. Previously directories present in default roles directory were treated as roles (dir name is role name).
Now scraper enters each directory looking for one of 8 specified subdirs. When at least one such subdir is found, its parent is treated as role, else subdir is added to search list (this is equivalent of traversing repository)
Adjusting tests to utilize nested role directories

scrape_role_files: add support for nested role directories

---

CHANGELOG.md
zubbi/models.py
zubbi/templates/search.html
zubbi/views.py

Zubbi-scraper is now able to parse roles that are defined in a nested 
directory structure. Those roles have a path-like name, e.g. foo/bar.
In order to show those roles properly in zubbi-web, we have to urlencode 
the role names in the URL for the details view and also escape the special
characters ("/") in the Elasticsearch query string. The latter one was
already done in other places, so this just aligns the details query with
the "normal" search query.

Make zubbi-web work with path-like role names
